#pragma once

#include <imgui.h>

#pragma region PROJECT_SELECTOR

#define SELECTOR_MAIN_COLOR ImVec4(25.0f / 255.0f, 25.0f / 255.0f, 25.0f / 255.0f, 1.0f)

#define SELECTOR_CREATE_BUTTONS_COLOR SELECTOR_MAIN_COLOR
#define SELECTOR_LIST_BOX_HEADER_BACKGROUND_COLOR SELECTOR_MAIN_COLOR
#define SELECTOR_LEFT_BUTTONS_COLOR SELECTOR_MAIN_COLOR
#define SELECTOR_BUTTON_HOVERED ImVec4(81.0f / 255.0f, 107.0f / 255.0f, 150.0f / 255.0f, 1.0f)

#define SELECTOR_FILEDIALOGE_BUTTON_COLOR SELECTOR_MAIN_COLOR
#define SELECTOR_LISTBOX_BACKGROUND_COLOR SELECTOR_MAIN_COLOR

#define SELECTOR_HEADER_COLOR SELECTOR_MAIN_COLOR

#pragma endregion

#pragma region REAL_TIME_EDITOR

#define REAL_EDITOR_BUTTON_BG_COLOR ImVec4(55.0f / 255.0f, 55.0f / 255.0f, 55.0f / 255.0f, 0.5f)

#pragma endregion